### PR TITLE
Updated all gatherX and wanderX methods to be parSequenceX and parTra…

### PR DESCRIPTION
**Pull request by Executioner1939**
#75 

@Avasil I see we don't have a `TaskDeprecated` object like `monix.eval`. I hope what I have done is correct.

I can add and implement the same Deprecation Strategy if you would like?

Please let me know if I should fix it :-)

### CODE REVIEW

**Comment by Avasil** [comment]
Thanks @Executioner1939 :) 

I just merged #101 with `wanderN` - could you add `parTraverseN` too?

> I can add and implement the same Deprecation Strategy if you would like?

Yes please, I didn't setup MiMa yet but I intend to keep binary compatibility here as well. We probably need similar mechanism for aliases (Task, UIO)

**Comment by Executioner1939** [comment]
@Avasil I have updated the PR :-).

I added three objects `BIODeprecated`, `UIODeprecated` and `TaskDeprecated`. I hope this is okay, I also set the deprecation since version to `0.1.0` not sure if it should be the next version number? If so are we just bumping up to `0.2.0`?

**Comment by Executioner1939** [comment]
@Avasil Hi :-). Anything I need to rectify here?

**Comment by Avasil** [comment]
> I also set the deprecation since version to 0.1.0 not sure if it should be the next version number? If so are we just bumping up to 0.2.0?

I plan to keep `0.1.x` until we break binary compatibility so it should be probably `0.1.1` but we'll see

**Pull request merged**
