### PR TITLE
Docusaurus website

### PR DESCRIPTION
**Pull request by Avasil**
Configuration is based on https://cir.is/ with small adjustements, we can play with color scheme later

### CODE REVIEW

**Comment by paualarco** [comment]
very cool! honestly, I thought it was going to take longer
looking forward to see it! :D

**Comment by Avasil** [comment]
@paualarco It's already up https://monix.github.io/monix-bio/ but it seems like CSS didn't apply and I need to correct few urls :D

**Comment by Avasil** [comment]
Okay, it seems to be fixed
Now I just have to fill it :D And we could play with colors to match the logo

**Comment by paualarco** [comment]
@Avasil OMG it looks amazing! <3

**Pull request merged**
